stages:
  - build-stage
  - test-stage
  - test
  - deploy-stage

build-job:
  stage: build-stage
  script:
    - echo "This is the build job"

test-job:
  stage: test-stage
  script:
    - echo "This is the test job"


deploy-job:
  stage: deploy-stage
  script:
    echo "This is the deploy job"

unallocated-job:
  script:
    echo "This is the unallocated job"