image: node

pre-job:
  stage: .pre
  script:
    - echo "This is the .pre job"

build-job:
  tags:
    - shared-windows
  stage: build
  script:
    - echo "This is the build job"
    - npm install
  artifacts:
    paths:
      - node_modules
      - package-lock.json


test-job:
  stage: test
  script:
    - echo "This is the test job"


deploy-job:
  stage: deploy
  script:
    echo "This is the deploy job"

unallocated-job:
  script:
    echo "This is the unallocated job"

post-job:
  stage: .post
  script:
    echo "This is the unallocated job"