variables:
  NAME: 'Gilbert'
  MESSAGE: 'Testing Custom variables'

display_variables:
  script:
    - echo $CI_COMMIT_MESSAGE
    - echo $CI_JOB_NAME
    - echo "Custom - Name is $NAME, and message is $MESSAGE"
  tags:
    - localrunner

secret_variables:
  script:
    - echo $GIL_SECRET_VAR
  tags:
    - localrunner

build:
  image: docker:latest
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - echo "The registry is $CI_REGISTRY"
  script:
    - docker build -t registry.gitlab.com/gtwesigomwe1/fedhr_django_guide .
    - docker images
    - docker push registry.gitlab.com/gtwesigomwe1/fedhr_django_guide
  tags:
    - localrunner