stages:
  - build_stage
  - deploy_stage

build:
  stage: build_stage
  script:
    - docker --version
    - docker build -t pyapp .
  tags:
    - localshell
    - localrunner

deploy:
  stage: deploy_stage
  script:
    - docker run -d --name pyappcontainer -p 6000:8099 pyapp
  tags:
    - localshell
    - localrunner