# FEDHR-NEW POSTGRES PVC ==============================================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fedhr-new-postgres-pvc
  namespace: fedhr-new
  labels:
    app: local
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: fedhr-new-postgres-pv
