# FEDHR-NEW POSTGRES PV ==============================================
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fedhr-new-postgres-pv
  namespace: fedhr-new
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgres-pv