# Generated by Django 3.2.13 on 2022-11-13 08:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('removed', models.BooleanField(default=False)),
                ('leave_category_name', models.CharField(max_length=255)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_visible_calendar', models.BooleanField(default=False)),
                ('track_time_in', models.CharField(choices=[('DAYS', 'Days'), ('HOURS', 'Hours')], max_length=10)),
                ('color', models.CharField(max_length=10)),
                ('icon', models.FileField(blank=True, null=True, upload_to='all_uploads')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('removed', models.BooleanField(default=False)),
                ('leave_policy_name', models.CharField(max_length=255)),
                ('accrued_amount', models.FloatField()),
                ('accrual_frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('EVERY_OTHER_WEEK', 'Every other week'), ('TWICE_A_MONTH', 'Twice a month'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quartely'), ('TWICE_A_AYEAR', 'Twice a year'), ('YEARLY', 'Yearly'), ('ON_HIRE_DATE_ANNIVERSARY', 'On Hire Date Anniversary'), ('PER_HOUR_WORKED', 'Per hour worked')], max_length=50)),
                ('weekly_day', models.CharField(blank=True, choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=50, null=True)),
                ('every_other_week_day', models.CharField(blank=True, choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=50, null=True)),
                ('every_other_week_day_start', models.CharField(blank=True, choices=[('IMMEDIATE', 'Immediate'), ('NEXT', 'Next')], max_length=50, null=True)),
                ('twice_amonth_day1', models.IntegerField(blank=True, null=True)),
                ('twice_amonth_day2', models.IntegerField(blank=True, null=True)),
                ('monthly_day', models.IntegerField(blank=True, null=True)),
                ('quartely_quarter1_month', models.CharField(blank=True, choices=[('JANUARY', 'January'), ('FEBUARY', 'February'), ('MARCH', 'March'), ('APRIL', 'April'), ('MAY', 'May'), ('JUNE', 'June'), ('JULY', 'July'), ('AUGUST', 'August'), ('SEPTEMBER', 'September'), ('OCTOBER', 'October'), ('NOVEMBER', 'November'), ('DECEMBER', 'December')], max_length=20, null=True)),
                ('quartely_quarter1_month_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('quartely_quarter2_month', models.CharField(blank=True, choices=[('JANUARY', 'January'), ('FEBUARY', 'February'), ('MARCH', 'March'), ('APRIL', 'April'), ('MAY', 'May'), ('JUNE', 'June'), ('JULY', 'July'), ('AUGUST', 'August'), ('SEPTEMBER', 'September'), ('OCTOBER', 'October'), ('NOVEMBER', 'November'), ('DECEMBER', 'December')], max_length=20, null=True)),
                ('quartely_quarter2_month_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('quartely_quarter3_month', models.CharField(blank=True, choices=[('JANUARY', 'January'), ('FEBUARY', 'February'), ('MARCH', 'March'), ('APRIL', 'April'), ('MAY', 'May'), ('JUNE', 'June'), ('JULY', 'July'), ('AUGUST', 'August'), ('SEPTEMBER', 'September'), ('OCTOBER', 'October'), ('NOVEMBER', 'November'), ('DECEMBER', 'December')], max_length=20, null=True)),
                ('quartely_quarter3_month_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('quartely_quarter4_month', models.CharField(blank=True, choices=[('JANUARY', 'January'), ('FEBUARY', 'February'), ('MARCH', 'March'), ('APRIL', 'April'), ('MAY', 'May'), ('JUNE', 'June'), ('JULY', 'July'), ('AUGUST', 'August'), ('SEPTEMBER', 'September'), ('OCTOBER', 'October'), ('NOVEMBER', 'November'), ('DECEMBER', 'December')], max_length=20, null=True)),
                ('quartely_quarter4_month_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('twice_ayear_first_half_month', models.CharField(blank=True, choices=[('JANUARY', 'January'), ('FEBUARY', 'February'), ('MARCH', 'March'), ('APRIL', 'April'), ('MAY', 'May'), ('JUNE', 'June'), ('JULY', 'July'), ('AUGUST', 'August'), ('SEPTEMBER', 'September'), ('OCTOBER', 'October'), ('NOVEMBER', 'November'), ('DECEMBER', 'December')], max_length=20, null=True)),
                ('twice_ayear_first_half_month_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('twice_ayear_second_half_month', models.CharField(blank=True, choices=[('JANUARY', 'January'), ('FEBUARY', 'February'), ('MARCH', 'March'), ('APRIL', 'April'), ('MAY', 'May'), ('JUNE', 'June'), ('JULY', 'July'), ('AUGUST', 'August'), ('SEPTEMBER', 'September'), ('OCTOBER', 'October'), ('NOVEMBER', 'November'), ('DECEMBER', 'December')], max_length=20, null=True)),
                ('twice_ayear_second_half_month_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('yearly_month', models.CharField(blank=True, choices=[('JANUARY', 'January'), ('FEBUARY', 'February'), ('MARCH', 'March'), ('APRIL', 'April'), ('MAY', 'May'), ('JUNE', 'June'), ('JULY', 'July'), ('AUGUST', 'August'), ('SEPTEMBER', 'September'), ('OCTOBER', 'October'), ('NOVEMBER', 'November'), ('DECEMBER', 'December')], max_length=20, null=True)),
                ('yearly_month_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_waiting_period_on', models.BooleanField(default=False)),
                ('waiting_period', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('waiting_period_unit', models.CharField(blank=True, choices=[('DAYS', 'Days'), ('WEEKS', 'Weeks'), ('MONTHS', 'Months'), ('YEARS', 'Years')], max_length=10, null=True)),
                ('is_accrual_balance_limit_on', models.BooleanField(default=False)),
                ('accrual_balance_limit', models.FloatField(blank=True, null=True)),
                ('carry_over_unused_time_off_after_carry_over_date', models.BooleanField(default=False)),
                ('is_carry_over_unused_time_off_limit_on', models.BooleanField(default=False)),
                ('carry_over_unused_time_off_up_to', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('carry_over_month', models.CharField(blank=True, choices=[('JANUARY', 'January'), ('FEBUARY', 'February'), ('MARCH', 'March'), ('APRIL', 'April'), ('MAY', 'May'), ('JUNE', 'June'), ('JULY', 'July'), ('AUGUST', 'August'), ('SEPTEMBER', 'September'), ('OCTOBER', 'October'), ('NOVEMBER', 'November'), ('DECEMBER', 'December')], max_length=20, null=True)),
                ('carry_over_month_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reset_negative_balances_to_zero_on_carry_over_day', models.BooleanField(default=False)),
                ('is_first_accrual_prorated', models.BooleanField(default=False)),
                ('accrual_time_received_at_start_or_end', models.CharField(blank=True, choices=[('START', 'Start'), ('END', 'End')], max_length=20, null=True)),
                ('is_transition_to_next_milestone_immediate', models.BooleanField(default=False)),
                ('leave_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeoff.leavecategory')),
            ],
        ),
        migrations.AddConstraint(
            model_name='leavepolicy',
            constraint=models.CheckConstraint(check=models.Q(('twice_amonth_day1__lte', 15)), name='twice_amonth_day1_should_be_15th_and_below'),
        ),
        migrations.AddConstraint(
            model_name='leavepolicy',
            constraint=models.CheckConstraint(check=models.Q(('twice_amonth_day2__gt', 15)), name='twice_amonth_day2_should_be_above_15th'),
        ),
    ]
