# Generated by Django 3.2.13 on 2022-11-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_add_fields_and_models_to_expand_employee_model'),
        ('timeoff', '0002_add_fields_add_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavepolicy',
            name='employees',
            field=models.ManyToManyField(related_name='leave_policies', to='employee.Employee'),
        ),
    ]
