# Generated by Django 3.2.13 on 2022-11-13 16:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_add_fields_and_models_to_expand_employee_model'),
        ('timeoff', '0004_leaverequest_inherit_basemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('removed', models.BooleanField(default=False)),
                ('current_balance', models.FloatField(default=0)),
                ('used', models.FloatField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('leave_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeoff.leavecategory')),
            ],
        ),
        migrations.AddConstraint(
            model_name='leavebalance',
            constraint=models.UniqueConstraint(fields=('employee', 'leave_category'), name='unique_employee_leave_category'),
        ),
    ]
