# Generated by Django 3.2.13 on 2022-11-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicationquestionanswer',
            name='answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
