# Generated by Django 3.2.13 on 2023-09-19 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0003_add_field_job_opening_question_ to_jobapplicationquestionanswer_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('removed', models.BooleanField(default=False)),
                ('template_name', models.CharField(max_length=255)),
                ('template', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
