# Generated by Django 3.2.13 on 2023-09-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0005_add_template_type_field_and_modify_template_field_on_template_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='available_positions',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='compensation_currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='internal_job_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='location_type',
            field=models.CharField(blank=True, choices=[('OFFICE', 'Office'), ('HYBRID', 'Hybrid'), ('REMOTE', 'Remote')], max_length=20, null=True),
        ),
    ]
