# Generated by Django 3.2.13 on 2024-03-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0007_add_field_compensation_type_to_jobopening_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='cover_letter',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='date_available',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='desired_salary',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='referred_by',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='resume',
        ),
        migrations.AddField(
            model_name='candidate',
            name='linkedin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.FileField(blank=True, null=True, upload_to='all_uploads'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='date_available',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='desired_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='referred_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='all_uploads'),
        ),
    ]
