# Generated by Django 3.2.13 on 2022-11-26 07:03

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0002_add_fields_and_models_to_expand_employee_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('removed', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeePayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('removed', models.BooleanField(default=False)),
                ('total_hours', models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=10)),
                ('overtime_hours', models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=10)),
                ('leave_hours', models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=10)),
                ('gross_pay', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=20)),
                ('overtime_pay', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=20)),
                ('leave_pay', models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_payrolls', to='employee.employee')),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_payrolls', to='payroll.payrollperiod')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
