# Generated by Django 3.2.13 on 2022-12-19 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_removed'),
        ('employee', '0002_add_fields_and_models_to_expand_employee_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_avatars', to='files.file'),
        ),
    ]
