# Generated by Django 3.2.13 on 2023-09-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_added_avatar_field_on_employee_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('COMMON_LAW', 'Common Law'), ('DOMESTIC_PARTNERSHIP', 'Domestic Partnership')], max_length=50, null=True),
        ),
    ]
