# Generated by Django 3.2.13 on 2023-09-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_modifed_start_date_and_end_date_on_education_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visainformation',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visainformation',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visainformation',
            name='issued_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
