# Generated by Django 3.2.13 on 2023-09-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_jobinformation_effective_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compensation',
            name='effectived_date',
        ),
        migrations.AddField(
            model_name='compensation',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
