# Generated by Django 3.2.13 on 2023-09-15 15:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_field_effective_date_on_compensation_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('removed', models.BooleanField(default=False)),
                ('relationship_name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='compensation',
            name='pay_rate_period',
            field=models.CharField(choices=[('DAY', 'Day'), ('WEEK', 'Week'), ('MONTH', 'Month'), ('QUARTER', 'Quarter'), ('YEAR', 'Year'), ('PAY_PERIOD', 'Pay Period'), ('PIECE', 'Piece')], max_length=50),
        ),
        migrations.AlterField(
            model_name='compensation',
            name='payment_method',
            field=models.CharField(choices=[('PAYCHECK', 'Paycheck'), ('DIRECT_DEPOSIT', 'Direct Deposit'), ('CASH', 'Cash')], max_length=50),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='relationship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.relationship'),
        ),
    ]
